// ─── DESIGN TOKENS ────────────────────────────────────────────────────────────
export const C = {
  red:      "#DA291C",
  redH:     "#C0392B",
  redLight: "#FEF2F2",
  redBorder:"#FECACA",
  white:    "#FFFFFF",
  bg:       "#F7F6F4",
  bgCard:   "#FFFFFF",
  bgStripe: "#FAFAF9",
  border:   "#E4E2DE",
  borderSm: "#EEECE9",
  ink:      "#18181B",
  inkMid:   "#52525B",
  inkSoft:  "#A1A1AA",
  inkFaint: "#D4D4D8",
  gold:     "#D4A843",
  goldLight:"#FEF3C7",
  L: [
    { c:"#EF4444", bg:"#FEF2F2", border:"#FECACA", text:"#991B1B", label:"Inicial",    desc:"La organización no cuenta con procesos formales para planificar y priorizar inversiones CAPEX. Las decisiones son reactivas y ad-hoc, sin vinculación a objetivos estratégicos ni criterios de priorización establecidos." },
    { c:"#F97316", bg:"#FFF7ED", border:"#FED7AA", text:"#9A3412", label:"Básico",     desc:"Existen lineamientos generales, pero los procesos de planificación CAPEX son informales e inconsistentes entre áreas. La priorización depende de criterios subjetivos y la trazabilidad de las decisiones de inversión es limitada." },
    { c:"#EAB308", bg:"#FEFCE8", border:"#FEF08A", text:"#854D0E", label:"Definido",   desc:"Los procesos CAPEX están documentados y son repetibles. Existe un roadmap tecnológico aprobado y las inversiones se alinean a hitos estratégicos. Las decisiones de priorización son transparentes y reproducibles entre ciclos." },
    { c:"#22C55E", bg:"#F0FDF4", border:"#BBF7D0", text:"#166534", label:"Gestionado", desc:"Las inversiones CAPEX se gestionan con KPIs explícitos y revisiones periódicas formales. Los desvíos se identifican y corrigen oportunamente. La organización toma decisiones basadas en datos históricos y proyecciones cuantitativas." },
    { c:"#3B82F6", bg:"#EFF6FF", border:"#BFDBFE", text:"#1E40AF", label:"Optimizado", desc:"El CAPEX está integrado al ciclo estratégico con feedback loops continuos. La organización optimiza su cartera con benchmarks de industria, aprende sistemáticamente de cada ciclo de inversión y anticipa necesidades futuras con modelos predictivos." },
  ],
};

export const FF = "'Segoe UI','Calibri',system-ui,sans-serif";

// ─── DATA ──────────────────────────────────────────────────────────────────────
export const RUBROS = [
  { key:"red_movil",    label:"Red Móvil",    icon:"📡", sub:"PEN · ODH · Crecimiento Orgánico · OyM Móvil" },
  { key:"red_fija",     label:"Red Fija",      icon:"🔌", sub:"Brownfield · Greenfield · HFC · OyM Fija" },
  { key:"transmision",  label:"Transmisión",   icon:"🔗", sub:"MW · Backbone · Troncal FO · Puertos" },
  { key:"nube_publica", label:"Nube Pública",  icon:"☁️", sub:"Datacenter · OCI · Obras Civiles · OyM" },
  { key:"nube_telco",   label:"Nube Telco",    icon:"🖥️", sub:"Telco Cloud · Crecimiento Orgánico" },
  { key:"it",           label:"IT",            icon:"💻", sub:"Salesforce · Analítica · Jugadas Estratégicas" },
  { key:"umm",          label:"UMM",           icon:"📦", sub:"Clientes FTTH · DTH · Migraciones" },
  { key:"umc",          label:"UMC",           icon:"🏗️", sub:"Proyectos de construcción y despliegue" },
];

export const CRITERIOS = [
  { num:"01", key:"alineacion", icon:"🎯", label:"Alineación Estratégica",
    desc:"Grado en que las iniciativas CAPEX están vinculadas a objetivos estratégicos del negocio y roadmaps tecnológicos.",
    vinc:"Levantamiento: Entendimiento de estrategia e impacto en NPS, ARPU e indicadores financieros",
    ndesc:["Sin vínculo formal entre inversión y estrategia. Proyectos ad-hoc sin validación estratégica.","Lineamientos generales de negocio pero sin traducción clara a objetivos por área tecnológica.","Roadmap por paquete aprobado. CAPEX alineado a hitos del plan estratégico.","Revisión periódica con ajuste presupuestal formal, documentado y con KPIs de alineación.","CAPEX integrado al ciclo de planeación estratégica con feedback loop continuo y benchmarks."],
    subs:[
      {id:"a1",t:"¿Las inversiones CAPEX están vinculadas explícitamente a objetivos estratégicos cuantificables (NPS, ARPU, cobertura, cuota de mercado)?",p:1.2,
       opp:"Crear una matriz CAPEX-KPI donde cada inversión tenga al menos un indicador de negocio comprometido (ej. +X puntos NPS, +Y% cobertura 5G, reducción de OPEX en Z%). Esto le da estructura al presupuesto y facilita la defensa del plan ante la dirección."},
      {id:"a2",t:"¿Existe un roadmap tecnológico por paquete aprobado formalmente como guía para la construcción del presupuesto CAPEX?",p:1.2,
       opp:"Sin roadmap aprobado por paquete, el CAPEX se construye bottom-up desde operaciones y pierde coherencia con la estrategia. Un roadmap por paquete reduce en ~30% las revisiones de alcance durante el año."},
      {id:"a3",t:"¿Se realiza revisión periódica (al menos anual) del alineamiento entre el plan estratégico y el presupuesto CAPEX aprobado?",p:1.0,
       opp:"Una revisión anual estructurada detecta inversiones que ya no responden a la estrategia vigente — en promedio el 15–20% del presupuesto construido queda desalineado entre ciclos sin este proceso."},
      {id:"a4",t:"¿Existen KPIs de alineación estratégica que midan si los proyectos CAPEX están entregando el valor comprometido al negocio?",p:1.0,
       opp:"Sin KPIs de valor, el CAPEX se evalúa solo por ejecución presupuestal, no por impacto. Definir 2–3 KPIs por categoría permite medir si los COP invertidos generan el retorno comprometido."},
      {id:"a5",t:"¿Las brechas entre la estrategia y la capacidad de inversión son identificadas, cuantificadas y escaladas formalmente?",p:0.9,
       opp:"Cuantificar formalmente las brechas de inversión permite construir un presupuesto realista: saber que faltan COP X para cumplir el objetivo de cobertura es diferente a intuirlo. Evita que proyectos estratégicos queden sin asignación por falta de visibilidad en la construcción del plan."},
      {id:"a6",t:"¿Las áreas de negocio y comerciales participan activamente en la definición y validación de los proyectos CAPEX?",p:0.8,
       opp:"En telcos, el 35–45% de proyectos CAPEX con mayor desviación son aquellos donde operaciones define la inversión sin input comercial. Incorporar a las áreas de negocio en la construcción del presupuesto reduce este riesgo y mejora la calidad de los estimados."},
      {id:"a7",t:"¿El plan CAPEX multianual (3–5 años) está alineado con la visión de largo plazo y revisado en ciclos IBP?",p:0.8,
       opp:"Un plan multianual integrado al IBP permite comprometer contratos marco con proveedores estratégicos (ej. Ericsson, Nokia, AWS) con 12–18 meses de anticipación, logrando ahorros de 8–15% en precios de equipos."},
    ]},
  { num:"02", key:"granularidad", icon:"🔬", label:"Granularidad y Desagregación",
    desc:"Nivel de detalle con el que se construye el presupuesto: por proyecto, subproyecto, componente tecnológico o categoría de gasto (PxQ).",
    vinc:"Levantamiento: Nivel de granularidad · DVB: Categorías, paquetes, drivers y PxQ · Árbol CAPEX",
    ndesc:["Presupuesto agregado por área tecnológica. Sin desagregación de proyectos ni componentes.","Detalle a nivel de proyecto pero sin clasificación por tipo de activo ni categoría.","Desglose por proyecto, tipo de activo (HW, SW, civil) y categoría tecnológica definida.","Detalle por subproyecto, fase, proveedor y WBS estructurado con drivers PxQ.","Granularidad a nivel SKU/componente con trazabilidad end-to-end y OBS/WBS integrado."],
    subs:[
      {id:"g1",t:"¿El presupuesto está desagregado hasta nivel de proyecto individual, con identificación de tipo de activo (HW, SW, obra civil)?",p:1.2,
       opp:"Sin desagregación por tipo de activo (HW/SW/civil), es imposible renegociar con proveedores o detectar dónde se generan los sobrecostos. Proyectos de fibra sin desglose civil vs. equipo típicamente acumulan 20–25% de desviación no explicada."},
      {id:"g2",t:"¿Se utilizan plantillas PxQ estandarizadas por tipo de proyecto o tecnología (nodo 5G, km de fibra, rack de datacenter)?",p:1.2,
       opp:"Las plantillas PxQ estandarizadas reducen el tiempo de formulación de presupuesto por paquete de semanas a días, y permiten comparar eficiencia entre regiones: ¿por qué un km de fibra cuesta 2x más en una región que en otra?"},
      {id:"g3",t:"¿Existe un árbol CAPEX y catálogo vigente de categorías y paquetes que estructure el presupuesto consistentemente?",p:1.1,
       opp:"Un árbol CAPEX desactualizado genera duplicidades entre paquetes (ej. inversión en transporte contada en Red Móvil y Transmisión simultáneamente). Un catálogo vigente elimina estas duplicidades y mejora la calidad del consolidado."},
      {id:"g4",t:"¿El nivel de granularidad permite identificar inversión por región geográfica, segmento de cliente o unidad de negocio?",p:1.0,
       opp:"Sin granularidad geográfica no se puede construir un presupuesto territorializado. Esta vista permite distribuir el CAPEX por región con criterios técnicos reales (demanda, cobertura, estado de red) y no solo por histórico del año anterior."},
      {id:"g5",t:"¿Las categorías de inversión (CAPEX directo, indirecto, OPEX capitalizado) están definidas y aplicadas consistentemente?",p:1.0,
       opp:"La mezcla incorrecta de CAPEX directo, indirecto y OPEX capitalizado puede distorsionar el EBITDA reportado en hasta 5–8 puntos porcentuales. La consistencia en categorías protege la integridad financiera ante auditorías y reguladores."},
      {id:"g6",t:"¿Se realizan reconciliaciones entre lo presupuestado PxQ y la ejecución real para calibrar precisión futura?",p:0.9,
       opp:"Las reconciliaciones PxQ vs. ejecución real revelan cuáles drivers son precisos y cuáles se sobreestiman sistemáticamente. En telcos, los drivers de obra civil suelen tener un sesgo optimista de 20–30% que se corrige con este proceso."},
      {id:"g7",t:"¿Los drivers de estimación están documentados y permiten trazabilidad completa desde el monto hasta los supuestos de base?",p:0.9,
       opp:"La falta de trazabilidad de drivers es el principal obstáculo cuando cambia el equipo de planeación. Documentar los supuestos permite que un analista nuevo reconstruya el presupuesto en horas, no en semanas."},
      {id:"g8",t:"¿Se realizan análisis de sensibilidad de drivers ante cambios externos (inflación, tipo de cambio, precios de equipos)?",p:0.7,
       opp:"Una depreciación del 10% en el tipo de cambio puede impactar entre 3–7% del CAPEX total en una telco con equipos importados. Sin análisis de sensibilidad, este riesgo llega como sorpresa al cierre del trimestre."},
    ]},
  { num:"03", key:"aprobacion", icon:"✅", label:"Proceso de Aprobación de CAPEX",
    desc:"Solidez del proceso mediante el cual los proyectos son identificados, documentados, evaluados técnicamente y formalmente incorporados al presupuesto CAPEX del ciclo.",
    vinc:"DVB: Categorías, paquetes, drivers y PxQ · Modelo de Gobierno TO-BE · Acta validación paquete piloto",
    ndesc:["Sin proceso formal. Proyectos entran al presupuesto por solicitud directa sin documentación ni evaluación técnica.","Listado de proyectos con descripción básica pero sin ficha técnica estandarizada ni criterios de validación.","Ficha técnica estándar por proyecto, validación de alcance y estimados, aprobación documentada por nivel.","Proceso estructurado con estimación detallada de alcance, cronograma, supuestos y riesgos técnicos validados.","Proceso de construcción integrado con WBS, OBS, drivers PxQ y trazabilidad completa desde supuesto hasta monto."],
    subs:[
      {id:"ap1",t:"¿Existe un proceso formal para identificar, registrar y evaluar proyectos candidatos al presupuesto CAPEX?",p:1.2,
       opp:"Sin proceso formal, los proyectos entran al presupuesto por influencia política o urgencia operativa. Formalizar la identificación asegura que cada proyecto ingrese con documentación técnica mínima y que el presupuesto consolidado sea consistente y auditable."},
      {id:"ap2",t:"¿Se elabora una ficha técnica estándar por proyecto antes de su inclusión al presupuesto, con estimación de alcance, cronograma, supuestos y riesgos técnicos?",p:1.2,
       opp:"Una ficha técnica estándar es la base mínima para construir un presupuesto confiable. Sin ella, los estimados de costo, alcance y cronograma varían según quien los elabora, generando un presupuesto inconsistente que se desvía desde el primer mes de ejecución."},
      {id:"ap3",t:"¿Existe un proceso estandarizado de estimación de costos por proyecto que incluya desglose por componente (HW, SW, obra civil, servicios) antes de ser incluido en el presupuesto?",p:1.1,
       opp:"Un proceso estandarizado de estimación de costos elimina la inconsistencia entre áreas: que Red Móvil y Transmisión usen metodologías distintas para estimar el mismo tipo de obra genera un presupuesto no consolidable. La estandarización es el fundamento de la precisión."},
      {id:"ap4",t:"¿Existen umbrales de aprobación por monto, con instancias de autorización diferenciadas por nivel (operativo/táctico/estratégico)?",p:1.1,
       opp:"Sin umbrales diferenciados, el 70% del tiempo del comité ejecutivo se consume en proyectos pequeños que podrían aprobarse en nivel operativo. Los umbrales liberan agenda directiva para las decisiones que realmente la requieren."},
      {id:"ap5",t:"¿El proceso de aprobación genera actas formales con compromisos, responsables y plazos auditables?",p:1.0,
       opp:"Las actas formales con responsables y plazos son el único mecanismo que convierte una decisión de comité en un compromiso ejecutable. Sin ellas, el 40% de los acuerdos no se implementa en el plazo definido."},
      {id:"ap6",t:"¿Existe un repositorio centralizado y actualizado de fichas de proyecto CAPEX accesible para todas las áreas que participan en la construcción del presupuesto?",p:0.9,
       opp:"Un pipeline visible permite detectar en tiempo real cuándo hay capacidad presupuestal liberada (por cancelaciones o retrasos) y reasignarla a proyectos en lista de espera, evitando subejecución al cierre del año."},
      {id:"ap7",t:"¿Se realiza una validación de cierre de proyecto que confirme que el alcance ejecutado corresponde al alcance presupuestado y que los activos fueron correctamente registrados?",p:0.8,
       opp:"La validación de cierre confirma que lo ejecutado coincide con lo presupuestado y que los activos están correctamente registrados en el balance. Sin este paso, el CAPEX queda en proceso de capitalización por meses, distorsionando el balance y el presupuesto del siguiente ciclo."},
    ]},
  { num:"04", key:"forecast", icon:"📈", label:"Exactitud del Forecast",
    desc:"Precisión histórica del CAPEX presupuestado vs. ejecutado y capacidad de anticipar y gestionar desviaciones durante el año.",
    vinc:"DVB: Construcción del modelo de gestión y seguimiento · Reforecast y KPIs de ejecución por paquete",
    ndesc:["Desviaciones >40%. Sin seguimiento sistemático de ejecución vs. presupuesto.","Desviaciones 25–40%. Revisión semestral sin reforecast ni análisis de causas.","Desviaciones 15–25%. Reforecast trimestral con causas de desviación documentadas.","Desviaciones 5–15%. Reforecast mensual con KPIs de ejecución por paquete.","Desviaciones <5%. Forecast dinámico con modelos predictivos y alertas tempranas."],
    subs:[
      {id:"f1",t:"¿Se mide sistemáticamente la desviación CAPEX presupuestado vs. ejecutado con seguimiento mensual por proyecto y paquete?",p:1.2,
       opp:"El seguimiento mensual por paquete detecta en el mes 2–3 lo que sin seguimiento solo se ve en el mes 9, cuando ya no hay tiempo de corregir. Telcos con este proceso logran subejecuciones <8% vs. >20% en las que no lo tienen."},
      {id:"f2",t:"¿Existe un proceso formal de reforecast con periodicidad definida que permita reprogramar ante desviaciones relevantes?",p:1.2,
       opp:"El reforecast formal permite reasignar presupuesto liberado (por retrasos de proveedor o cambios regulatorios) a proyectos con mejor ritmo de ejecución, manteniendo la ejecución global por encima del 90% del plan."},
      {id:"f3",t:"¿Las causas de desviación son clasificadas y documentadas sistemáticamente (retrasos de proveedor, cambios de alcance, etc.)?",p:1.1,
       opp:"Clasificar causas de desviación revela si el problema es sistémico (mismo proveedor retrasa múltiples proyectos) o puntual. Esta información es la base para renegociar SLAs contractuales y mejorar la selección de proveedores."},
      {id:"f4",t:"¿Existen KPIs de ejecución presupuestal accesibles en tiempo real para los responsables de cada paquete tecnológico?",p:1.0,
       opp:"Los KPIs en tiempo real eliminan el lag de 3–4 semanas entre que ocurre una desviación y que llega al reporte mensual. Este lag es exactamente el tiempo que se pierde para tomar acción correctiva."},
      {id:"f5",t:"¿Se utilizan datos históricos de ejecución (mínimo 3 años) para calibrar estimados y mejorar el forecast del siguiente ciclo?",p:1.0,
       opp:"El sesgo optimista en los estimados de CAPEX (subestimar costos y plazos) es universal. Calibrar con 3+ años de histórico reduce este sesgo hasta en 40%, mejorando la credibilidad del área ante el CFO y el board."},
      {id:"f6",t:"¿Existen alertas automáticas ante desviaciones relevantes (>10% acumulado) durante la ejecución del presupuesto?",p:0.9,
       opp:"Las alertas automáticas ante desviaciones >10% permiten escalar en días, no en semanas. En proyectos de infraestructura con hitos contractuales, esta diferencia puede evitar penalidades por incumplimiento."},
      {id:"f7",t:"¿Se realizan análisis de sensibilidad ante cambios en variables clave (tipo de cambio, precios de equipos, demanda)?",p:0.7,
       opp:"Una depreciación inesperada del COP o un alza en precios de semiconductores puede invalidar el presupuesto aprobado en semanas. Los análisis de sensibilidad permiten activar planes de contingencia antes de que el impacto sea irrecuperable."},
    ]},
  { num:"05", key:"riesgos", icon:"⚠", label:"Gestión de Riesgos",
    desc:"Capacidad de identificar, cuantificar y gestionar riesgos que puedan afectar el monto, cronograma o alcance del CAPEX.",
    vinc:"Levantamiento: Modelo de gestión CAPEX · DVB: Gestión y seguimiento · Registro de riesgos y planes de mitigación",
    ndesc:["Sin análisis de riesgos. Sin provisiones para contingencias en el proceso de presupuestación.","Contingencia genérica (% fijo global) sin análisis diferenciado por proyecto o paquete.","Análisis por proyecto con contingencias diferenciadas según categoría tecnológica.","Registro activo, planes de mitigación y contingencias revisadas trimestralmente.","Simulación Monte Carlo / análisis de sensibilidad integrado al proceso de aprobación."],
    subs:[
      {id:"r1",t:"¿Existe proceso formal de identificación y análisis de riesgos que afecten el presupuesto CAPEX (retrasos, sobrecostos, regulatorio)?",p:1.2,
       opp:"Sin identificación formal de riesgos, los proyectos CAPEX en telco enfrentan sus principales amenazas sin plan: retrasos en permisos municipales, escasez de equipos por crisis de supply chain, o cambios regulatorios de última hora."},
      {id:"r2",t:"¿Las contingencias están diferenciadas por tipo de proyecto o paquete (no un % genérico global)?",p:1.1,
       opp:"Aplicar el mismo % de contingencia a un proyecto de fibra urbana y a uno de nube pública es equivalente a no tener contingencia diferenciada. Los proyectos de obra civil tienen 3–4x más variabilidad que los de software — la contingencia debe reflejarlo."},
      {id:"r3",t:"¿Se mantiene un registro activo de riesgos por proyecto con planes de mitigación y responsables asignados?",p:1.1,
       opp:"Un registro activo de riesgos con responsable nombrado convierte 'puede pasar' en 'alguien está encargado de que no pase'. Sin responsable, el 80% de los riesgos identificados no tiene seguimiento real."},
      {id:"r4",t:"¿Los riesgos y planes de mitigación son revisados con periodicidad definida en instancias formales del comité CAPEX?",p:1.0,
       opp:"La revisión periódica de riesgos en comité detecta cuando un riesgo latente se convierte en inminente, permitiendo activar mitigaciones antes del impacto. Sin revisión, la primera señal suele ser el retraso ya materializado."},
      {id:"r5",t:"¿Se realizan análisis de sensibilidad ante la materialización de riesgos clave (tipo de cambio, licencias, suministro global)?",p:0.9,
       opp:"Para una telco con CAPEX en USD/EUR y flujos en COP, una devaluación del 15% puede representar COP 50–100B de impacto no presupuestado. Cuantificar este riesgo con antelación permite negociar coberturas o ajustar el plan."},
      {id:"r6",t:"¿El proceso incorpora lecciones aprendidas de proyectos anteriores para mejorar la gestión de riesgos actuales?",p:0.8,
       opp:"Las lecciones aprendidas son el activo más subvalorado en construcción de presupuesto CAPEX. Saber que los proyectos de migración HFC tienen un 35% de sobrecosto histórico cambia radicalmente los estimados del siguiente ciclo — sin este input, el presupuesto repite los mismos errores."},
      {id:"r7",t:"¿Existe metodología de valoración de riesgos (probabilidad × impacto) aplicada consistentemente en todos los proyectos?",p:0.7,
       opp:"Sin metodología uniforme de probabilidad × impacto, cada área califica sus riesgos con criterios distintos y la comparación entre proyectos es imposible. La estandarización permite al comité tomar decisiones de mitigación con base en valor en riesgo real."},
    ]},
  { num:"06", key:"gobernanza", icon:"🏛", label:"Gobernanza CAPEX",
    desc:"Madurez del modelo de gobernanza para aprobación, seguimiento, reprogramación y cierre de proyectos CAPEX por paquete tecnológico.",
    vinc:"DVB: Proceso óptimo CAPEX, RACI y Torre de Control integrado a IBP · Modelo de gobierno TO-BE",
    ndesc:["Sin instancias formales. Decisiones ad-hoc sin trazabilidad ni RACI definida.","Comité esporádico. Actas sin seguimiento de acuerdos ni responsables.","Comité CAPEX periódico con roles, umbrales de aprobación y actas formales.","Governance multinivel (operativo, táctico, estratégico) con dashboards integrados.","Governance integrado al IBP con revisiones en hitos clave del ciclo presupuestal, calendario oficial y Torre de Control activa."],
    subs:[
      {id:"go1",t:"¿Existe un modelo de gobernanza CAPEX formalizado con RACI para cada etapa del ciclo presupuestal?",p:1.2,
       opp:"Sin RACI, los procesos de aprobación CAPEX acumulan delays porque nadie sabe con certeza quién debe decidir en cada etapa. En telcos, esto genera colas de aprobación que retrasan el inicio de proyectos entre 4–8 semanas."},
      {id:"go2",t:"¿Se realizan comités CAPEX periódicos con umbrales de aprobación por nivel de inversión y actas formales?",p:1.2,
       opp:"Los comités CAPEX sin umbrales definidos consumen tiempo directivo en decisiones que deberían resolverse operativamente. Un modelo bien calibrado reduce la agenda ejecutiva en CAPEX en 40–50% sin perder control sobre las decisiones críticas."},
      {id:"go3",t:"¿Existe una Torre de Control centralizada que consolide, valide y priorice el portfolio CAPEX?",p:1.2,
       opp:"Sin Torre de Control, cada paquete gestiona su CAPEX de forma aislada y el CFO no tiene visibilidad consolidada en tiempo real. La Torre de Control es la única manera de detectar solapamientos, reasignar recursos y anticipar cierres de año."},
      {id:"go4",t:"¿El proceso de governance CAPEX está integrado formalmente con los ciclos de IBP y el calendario presupuestal?",p:1.1,
       opp:"El desacople entre el governance CAPEX y el IBP genera el problema más costoso en planeación: decisiones de inversión que se toman fuera del ciclo presupuestal y terminan como adiciones no financiadas o cambios de alcance de último minuto."},
      {id:"go5",t:"¿El modelo incluye instancias diferenciadas por nivel (operativo, táctico, estratégico) con dashboards específicos?",p:1.0,
       opp:"Un dashboard operativo con granularidad de proyecto y un dashboard estratégico con visión de portafolio son herramientas distintas para audiencias distintas. Mezclarlos satura a los ejecutivos con información que no pueden consumir y oculta las señales críticas."},
      {id:"go6",t:"¿Existe proceso formal de cierre de proyectos con reconciliación financiera y captura de lecciones aprendidas?",p:0.9,
       opp:"El cierre formal de proyectos es el paso que más frecuentemente se omite en telcos. Sin él, los activos quedan en proceso de capitalización por meses, afectando el balance, y las contingencias no liberadas distorsionan el presupuesto del siguiente ciclo."},
      {id:"go7",t:"¿Hay un calendario presupuestal oficial con hitos de entrega, revisión y aprobación respetado por todas las áreas?",p:0.8,
       opp:"Sin calendario presupuestal respetado, el proceso de consolidación se convierte en una carrera de último minuto donde el 30–40% de los proyectos entra sin revisión adecuada. La calidad del presupuesto consolidado es directamente proporcional al cumplimiento del calendario."},
      {id:"go8",t:"¿Los acuerdos de comités CAPEX tienen responsables nombrados y se verifica su cumplimiento en la siguiente sesión?",p:0.7,
       opp:"Verificar el cumplimiento de acuerdos en la siguiente sesión es el mecanismo más simple y más ignorado de accountability. Sin este seguimiento, el comité CAPEX se convierte en un foro de presentación, no en un órgano de decisión con consecuencias."},
    ]},
];

// ─── HELPERS ──────────────────────────────────────────────────────────────────
export const wavg = (subs, ans) => {
  let t=0, w=0;
  subs.forEach(s => { const v=ans?.[s.id]; if(v>0){t+=v*s.p; w+=s.p;} });
  return w ? t/w : 0;
};

export const lv = v => C.L[Math.max(0, Math.min(4, Math.round(v)-1))];

export const getRubroData = (data, rubroKey) => {
  if (!data) return null;
  return data.ans?.[rubroKey] || data[rubroKey] || null;
};
